name: CI
on: push
jobs:
  linting:
    # runs-on: ubuntu-latest    # v1.0
    # runs-on: ${{ matrix.os }}   # v2.0
    runs-on: ${{ matrix.os }}   # v3.0

    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]   # v2.0
        os: [ubuntu-latest, windows-latest]   # v3.0
        version: ["3.9", "3.10", "3.11"]    # v3.0

    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          # python-version: "3.10"    # v1.0
          python-version: ${{ matrix.version }}   # v3.0

      - name: install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: run flake8
        run: |
          flake8 app.py

  

